version: '3.4'

services:
  flutterweb:
    container_name: flutterweb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./flutterweb:/usr/src/app
      - ./shared:/shared
      - /usr/src/app
    ports:
      - 8089:3000
